language: cpp

compiler:
    - arm-none-eabi-gcc

addons:
    apt_packages:
        - lib32bz2-1.0
        - lib32ncurses5
        - lib32z1
        - arm-none-eabi-gcc

install:
    - git clone https://github.com/R2D2-2019/R2D2-build.git 

script:
    - cd test
    - make build 
    - make clean
