language: cpp

compiler:
    - arm-none-eabi-gcc

addons:
    apt_packages:
        - lib32bz2-1.0
        - lib32ncurses5
        - lib32z1

before_script:
    - wget https://github.com/Infineon/Assets/releases/download/current/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.-d-.tar.bz2 -O /tmp/gcc-arm-none-eabi.tar.bz2
    - tar -xvjf /tmp/gcc-arm-none-eabi.tar.bz2
    - export PATH=$PATH:$PWD/gcc-arm-none-eabi-5_4-2016q3/bin/ 

install:
    - git clone https://github.com/R2D2-2019/R2D2-build.git 

script:
    - cd test
    - make build 
    - make clean
